---
swagger: "2.0"
info:
  description: This is a sample grunts server. 
  version: 1.0.0
  title: Swagger Grunts
  contact:
    email: wind.kaisa@gmail.com
  license:
    name: MIT License
    url: https://mit-license.org/
host: localhost:8080
basePath: /v1
consumes:
  - application/json
produces:
  - application/json
tags:
- name: user
  description: Operations about user
- name: oauth
  description: Operations about auth
- name: role
  description: Operations about role
- name: policy
  description: Operations about policy
schemes:
- http
paths:
  /rule:
    delete:
      tags:
      - rule
      summary: delete rule
      description: delete rule
      operationId: deleteRole
      produces:
      - application/json
      parameters:
      - name: user_id
        in: query
        description: user id
        required: true
        type: string
      - name: rule_name
        in: query
        description: rule name
        required: true
        type: string
      - name: type
        in: query
        description: rule type
        required: true
        type: string
      - name: domain_id
        in: query
        description: domain id
        required: true
        type: string
      responses:
        200:
          description: OK
        default:
          description: successful operation
      security:
      - Password:
        - read

securityDefinitions:
  Basic:
    type: basic
  Password:
    type: oauth2
    tokenUrl: https://www.kaisawind.com/v1/token
    flow: password
    scopes:
      read: Grants read access
      write: Grants write access

definitions:
  Principal:
    description: principal for token
    type: object
    properties:
      username:
        type: string
